/**:
  ros__parameters:
    timeout: 1000
    frame_rate_ms: 10 ## ms
    save_directory: '/home/arata22/recording/images'
    video_mode: 'VIDEOMODE_800x600YUV422'
    frame_rate: 'FRAMERATE_30'
    show_window: true

    right_camera_serial: ""
    left_camera_serial: ""


## VIDEO_MODEのリストをすべて列挙する
# VIDEOMODE_160x120YUV444
# VIDEOMODE_320x240YUV422
# VIDEOMODE_640x480YUV411
# VIDEOMODE_640x480YUV422
# VIDEOMODE_640x480RGB
# VIDEOMODE_640x480Y8
# VIDEOMODE_640x480Y16
# VIDEOMODE_800x600YUV422
# VIDEOMODE_800x600RGB
# VIDEOMODE_800x600Y8
# VIDEOMODE_800x600Y16
# VIDEOMODE_1024x768YUV422
# VIDEOMODE_1024x768RGB
# VIDEOMODE_1024x768Y8
# VIDEOMODE_1024x768Y16
# VIDEOMODE_1280x960YUV422
# VIDEOMODE_1280x960RGB
# VIDEOMODE_1280x960Y8
# VIDEOMODE_1280x960Y16
# VIDEOMODE_1600x1200YUV422
# VIDEOMODE_1600x1200RGB
# VIDEOMODE_1600x1200Y8
# VIDEOMODE_1600x1200Y16
# VIDEOMODE_FORMAT7

## FRAME_RATEのリストをすべて列挙する
# FRAMERATE_1_875
# FRAMERATE_3_75
# FRAMERATE_7_5
# FRAMERATE_15
# FRAMERATE_30
# FRAMERATE_60
# FRAMERATE_120
# FRAMERATE_240


